### ISSUE TITLE
Add GITHUB_TOKEN permissions to workflow

### ISSUE THREAD

**Issue by duffney** [bytecodealliance/sample-wasi-http-rust#13]
When you use the template the action permissions defaults to read only. Which prevents you from publishing artifacts to ghcr. To avoid that, we can add this to the workflow file so when the template is used it already gives the token the proper permissions. 

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
```
